### ISSUE TITLE
iPhone app not working properly

### ISSUE THREAD

**Issue by prepstarr** [jellyfin/jellyfin-expo#576]
**Describe the bug**

If the application is not in focus or the phone gets locked then program audio will stop. So cannot go for a walk and listen or fold clothes phone will automatically lock or check an email while listening… etc..

**System (please complete the following information):**
 - iOS Version:18.11
 - Jellyfin Expo version:latest
 - Jellyfin Server version: latest

**To Reproduce**

2. Tap on '....'

**Expected behavior**

It should work

**Screenshots**

**Additional context**

**Comment by thornbill** [comment]
Duplicate of #19
